# Generated by Django 5.0.4 on 2024-04-28 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_customuser_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='music_country',
            field=models.FileField(default=1, upload_to='musics/'),
            preserve_default=False,
        ),
    ]
