# Generated by Django 5.0.4 on 2024-04-28 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_playlist_prime_music_alter_playlist_music_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='prime_plus',
            field=models.BooleanField(default=False),
        ),
    ]
